[package]
name = "iec60870-5-102"
version = "0.1.0"
authors = ["anton"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
chrono = "0.4.11"
syn = "1.0"
quote = "1.0"

[build-dependencies]
handlebars = "3.1.0-beta.1"
serde_json = "1.0"